Updated tests

diff --git a/run-tests b/run-tests
--- a/run-tests
+++ b/run-tests
@@ -1,8 +1,8 @@
 # Created by: WestleyR
 # email: westleyr@nym.hush.com
-# Date: Sep 15, 2019
-# https://github.com/WestleyR/list-files
-# Version-1.0.1
+# Date: Nov 16, 2019
+# https://github.com/WestleyR/txtlinter
+# Version-1.0.0
 #
 # The Clear BSD License
 #
@@ -12,35 +12,40 @@
 # This software is licensed under a Clear BSD License.
 #
 
-# Check and insure 'bc' is installed, if not, the tests that
-# need bc will skip
-if ! command -v "bc"; then
-	echo "WARNING: 'bc' not found in PATH, bc is needed for some tests"
-fi
-
 echo "Running all tests..."
 echo
+
+mkdir tests/tmp
 
 all_tests_num=0
 tests_failed_num=0
 tests_failed=""
 
-test_files=`ls -1 tests/ | sort -n`
+#test_files=`ls -1 tests/ | sort -n`
+#
+#for t in $test_files; do
+#	if [ -f "tests/${t}" ]; then
+#		echo "Testing: ${t}:"
+#		if ! bash "tests/${t}"; then
+#			echo "test failed: ${t}"
+#			((tests_failed_num+=1))
+#			tests_failed=`echo "${test_failed} ${t}"`
+#		fi
+#		((all_tests_num+=1))
+#	fi
+#done
 
-for t in $test_files; do
-	if [ -f "tests/${t}" ]; then
-		echo "Testing: ${t}:"
-		if ! bash "tests/${t}"; then
-			echo "test failed: ${t}"
-			((tests_failed_num+=1))
-			tests_failed=`echo "${test_failed} ${t}"`
-		fi
-		((all_tests_num+=1))
-	fi
-done
+if ! bash "tests/1.basic"; then
+	echo "test failed: 1.basic"
+	((tests_failed_num+=1))
+fi
+((all_tests_num+=1))
+
 
 echo
 echo "All tests ran with ${tests_failed_num} test(s) failed (or skipped), of ${all_tests_num}"
+
+rm -rf tests/tmp
 
 if [[ $tests_failed_num -ge 1 ]]; then
     echo "FAILED TO RUN ALL TESTS"
